### ISSUE TITLE
Allow for multiple backup policies

### ISSUE THREAD

**Issue by calind** [bitpoke/mysql-operator#173]
If we do backup cleanup, I want to be able to say that I want to keep last 12 hourly backups, and last 7 daily backups.

**Comment by mnaser** [comment]
hi there :)

is this something that's possible by now, or at least the ability of saying "i want to keep the last N backups at this schedule" at least?

**Comment by AMecea** [comment]
Hi @mnaser, this is not possible right now but you can specify how many backups to be kept, see this [example](https://github.com/presslabs/mysql-operator/blob/3c3ba745ed15d5e438f5c7ba8f1bd8431ee7a462/examples/example-cluster.yaml#L19).

**Comment by calind** [comment]
Closing this in favor of #726 which will get added in 0.6.
