### ISSUE TITLE
Controlled configuration changes

### ISSUE THREAD

**Issue by mnaser** [bitpoke/mysql-operator#404]
Hi there

Love the operator, we use it quite a lot, but I think something that we're lacking is the fact that when making changes, we have this weird issue where if you're running with replica of 2:

- change `foo` setting in `mysqlConf`
- statefulset starts updating, `-1` is terminated
- `-1` was master, `-0` is promoted to master because `-1` is gone
- `-1` is back up as slave, `-0`  is dead again and now no master again

I'm not sure what the best way to go about this to prevent this from happening.. I'd be happy to put in the work to fix it

**Comment by AMecea** [comment]
Hi @mnaser,

We thought about this and concluded that `Deployment` rolling update is not a good fit. We should use `OnDelete` policy and let the operator choose the order in which the pods are killed (updated).

**Comment by AMecea** [comment]
If you would like to implement this feel free to open a PR or let's chat about this here or on the k8s Slack channel for #mysql-operator.

**Comment by cu12** [comment]
I was wondering your opinion about what if read-only/startup settings would need an extra variable set to `true` in order to push them live, and changes that could be done on-the-fly could be done within reconciliation.

**Comment by AMecea** [comment]
Hi @cu12, can you please elaborate a bit on your idea and how do handle this? I don't think I get it. :smile:
