### ISSUE TITLE
upgrading operator issue

### ISSUE THREAD

**Issue by Jacklli** [bitpoke/mysql-operator#529]
When upgraded operator with helm/charts, the mysql cluster rolling update come along, and failed.

Actually,  mysql cluster should not rolling update after operator upgrading.

Could you please help have a look at it ?

**Comment by AMecea** [comment]
Hi @Jacklli, this is indeed an issue that we encountered in the last few months too.

From what version to what version did you upgrade the operator?

We will try to keep it as follows, for upgrading the operator for:
 * PATCH versions (e.g. `v0.3.2` -> `v0.3.3` or `v0.3.4`): no restart of the MySQL cluster
 * MINOR versions (e.g. `v0.3.2` -> `v0.4.0`): the MySQL cluster will get restarted
 * MAJOR versions (e.g. `v0.5.0` -> `v1.0.0`): the MySQL cluster will get restarted and it may required manual intervention.

This didn't happen for all versions but for now on we will try to keep this that way.

**Comment by daanemanz** [comment]
@AMecea we've run into a similar issue; the version of the operator image is not explicitly set in the Helm chart (which just specifies `latest`) which also means that a _redeploy_ of the operator pod could upgrade (due to the `latest` tag) and trigger a rolling restart of the cluster.
