### ISSUE TITLE
More refined retention policy for backups

### ISSUE THREAD

**Issue by asoltesz** [bitpoke/mysql-operator#575]
The current backup retention options seem to be very limited (though I am new to this operator, I apologize if I missed something).

One option the retain all of the older backups which results in huge storage space wasting and manual backup deletions.

The other option to delete all backups when a new backup arrives. This will not allow keeping any of the older backups that could protect against running data corruptions and mistakes realized after a new backup is taken.

Similar backup software like pgBackrest (used in the Crunchydata Postgres Operator) allows for sophisticated backup retention policies with time based and backup-count based retention policies and daily/weekly/monthly/yearly backup retention configuration that maintains the backup repository and keeps storage space wasting to a minimum.

Would be nice to have something similar or at least some minimal, time based retention policy for daily backups.

**Comment by AMecea** [comment]
Hi @asoltesz, we plan to add support for backup policies, see #173 

For now, you can specify how many backups to keep, see [this config field](https://github.com/presslabs/mysql-operator/blob/3c3ba745ed15d5e438f5c7ba8f1bd8431ee7a462/examples/example-cluster.yaml#L19) on the MySQL cluster resource and you can set [delete policy](https://github.com/presslabs/mysql-operator/blob/3c3ba745ed15d5e438f5c7ba8f1bd8431ee7a462/examples/example-cluster.yaml#L20) to [`delete`](https://pkg.go.dev/github.com/presslabs/mysql-operator@v0.4.0/pkg/apis/mysql/v1alpha1?tab=doc#DeletePolicy) to remove them from remote storage.

**Comment by calind** [comment]
Closing this in favor of #726 which will get added in 0.6.
