### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by 15767637775** [bitpoke/mysql-operator#615]
Just getting started

$helm install mysql-operator presslabs/mysql-operator 

$kubectl get po mysql-operator-0 
NAME               READY   STATUS             RESTARTS   AGE
mysql-operator-0   1/2     CrashLoopBackOff   221        18h

$ kubectl logs mysql-operator-0 -c orchestrator
2020-10-20 01:19:48 FATAL unable to open database file

nothing else logs, how can I fix it?

**Comment by AMecea** [comment]
Hi @15767637775, can you tell me more about your environment (e.i k8s version, provider, underlaying storage)?

Also, you can try by disabling Orchestrator's persistance to test if that's the cause. Follow this comment: https://github.com/presslabs/mysql-operator/issues/610#issue-709704023 

Please let me know if this works. Usually, Orchestrator works without persistence but is not encourage to run in production without it.

**Comment by LERSONG** [comment]
> Hi @15767637775, can you tell me more about your environment (e.i k8s version, provider, underlaying storage)?
> 
> Also, you can try disabling Orchestrator's persistence to test if that's the cause. #610 is a discussion related to this. And you can disable persistence by setting [this value](https://github.com/presslabs/mysql-operator/blob/dfdea2b24bbd3981bbbbca56ee4f529e00430db9/charts/mysql-operator/values.yaml#L117) on `false`. Here's how the install command will look like:
> 
> ```
> $ helm install mysql-operator presslabs/mysql-operator --set orchestrator.persistence.enabled=false
> ```
> 
> Please let me know if this works. Usually, Orchestrator works without persistence but is not encourage to run in production without it.

it worked

**Comment by xdimedrolx** [comment]
I have the same problem for v0.5.0-rc.2. My environment: k8s 1.17.9, persistent storage - OpenStack Cinder.

**Comment by apurwaj2** [comment]
I have the same problem with with k8s version 1.20.2

**Comment by apurwaj2** [comment]
> I have the same problem with with k8s version 1.20.2. I do not wish to disable the persistence field but it would be better to know the underlying issue.

I could move past this hurdle, did not have write permissions on the PV created. Once I changed that I could proceed ahead.
