### ISSUE TITLE
Support Semantic Versioning

### ISSUE THREAD

**Issue by cndoit18** [bitpoke/mysql-operator#697]
https://github.com/presslabs/mysql-operator/blob/573f14bd883354329865038a6507d94a2fd9218b/Makefile#L1

The current version generation is not a semantic version, which can cause problems when updating the chart version number

**Comment by cndoit18** [comment]
can I use this tool? @AMecea 
https://github.com/mdomke/git-semver

**Comment by calind** [comment]
I think it's a good idea. Can you make a PR against https://github.com/bitpoke/build which is the build system used by MySQL operator. The versioning logic is in `makelib/common.mk`.
