### ISSUE TITLE
Point-in-time-recovery on Operator 0.4.0

### ISSUE THREAD

**Issue by venksel** [bitpoke/mysql-operator#712]
Hi there,
I'm using Presslabs MySql operator 0.4.0 with Mysql db percona:5.7.29 and I understand point in time recovery is supported.

However, don't see any documentation around how to perform the recovery. It would be great if someone points me in the right direction with the point-in-time recovery documentation.

Thanks folks for your help in advance! Appreciate it.

**Comment by cndoit18** [comment]
This should be a very useful feature 👍

**Comment by cndoit18** [comment]
Now there should be no support for this

**Comment by cndoit18** [comment]
repeated issues #7
