### ISSUE TITLE
MySQL operator runs on k8s 1.13 cluster. The operator reports an error " error initially creating leader selection"

### ISSUE THREAD

**Issue by 123fish** [bitpoke/mysql-operator#714]
Because k8s version of the current environment does not support 1.16, so modify CRD resource  and MySQL operator is deployed on the cluster of k8s version 1.13, but the operator reports some errors，
“Failed to update lock: the server could not find the requested resource”,
"error initially creating leader election record:the server could not find the requested resource"

Please help answer

**Comment by cndoit18** [comment]
The operator does not support k8s 1.13

**Comment by 123fish** [comment]
> The operator does not support k8s 1.13

Can I modify the code to be compatible?

**Comment by cndoit18** [comment]
> > The operator does not support k8s 1.13
> 
> Can I modify the code to be compatible?

You can fork a copy of yourself to make it compatible
