### ISSUE TITLE
"templates/layout" is undefined after upgrade to v0.5.1

### ISSUE THREAD

**Issue by haslersn** [bitpoke/mysql-operator#741]
I upgraded mysql-operator from 0.4.0 to 0.5.1. Now, when accessing the orchestrator web UI, I get redirected to `/web/clusters` where I obtain a response with status code 500 and payload:

```
html/template: "templates/layout" is undefined
```

**Comment by abh** [comment]
thanks @haslersn; that fixed it for me as well.
