### ISSUE TITLE
CRD error on 1.20.11

### ISSUE THREAD

**Issue by abh** [bitpoke/mysql-operator#753]
Applying the CRD from the repository gives me this error:

`The CustomResourceDefinition "mysqlclusters.mysql.presslabs.org" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema`

**Comment by calind** [comment]
This is fixed in b425626f23f4fd2438108f7a0472c71f26fe22f7 and released in v0.5.3.
