### ISSUE TITLE
Change BackupRemoteDeletePolicy but didn't work

### ISSUE THREAD

**Issue by navist2020** [bitpoke/mysql-operator#774]
If I specify under crontab to take backups. I noticed that the following fields need to be set
https://github.com/bitpoke/mysql-operator/blob/d8ec7b442aa2130a406442e58396336b555ff13b/pkg/apis/mysql/v1alpha1/mysqlcluster_types.go#L74-L96
When I edit the `BackupRemoteDeletePolicy` (The default is `retain` but I want to change it to `delete`). This modification didn't work.The `remoteDeletePolicy` inside the new `mysqlbackup` object is still the same as the original value.I have tried several times with the same result. Is it just me, or is this the desired result?

**Comment by navist2020** [comment]
`BackupURL` and `BackupSecretName` are both set in `MysqlBackup` controller,  and they work fine after modification.
https://github.com/bitpoke/mysql-operator/blob/d8ec7b442aa2130a406442e58396336b555ff13b/pkg/internal/mysqlbackup/defaults.go#L24-L30
But `BackupRemoteDeletePolicy` is set in `MysqlBackupCron` controller
https://github.com/bitpoke/mysql-operator/blob/d8ec7b442aa2130a406442e58396336b555ff13b/pkg/controller/mysqlbackupcron/job_backup.go#L83-L98
Is this the cause of the problem?

**Comment by navist2020** [comment]
I think the cause of the problem may be here.
This function could add a logic to compare whether `j.BackupRemoteDeletePolicy` is the same or not
https://github.com/bitpoke/mysql-operator/blob/d8ec7b442aa2130a406442e58396336b555ff13b/pkg/controller/mysqlbackupcron/mysqlbackupcron_controller.go#L154-L199
Or we can set the default value of `RemoteDeletePolicy` in this function.
https://github.com/bitpoke/mysql-operator/blob/d8ec7b442aa2130a406442e58396336b555ff13b/pkg/internal/mysqlbackup/defaults.go#L24-L30
`RemoteDeletePolicy` belongs to `MysqlBackupSpec`. I think this approach might be better?(not sure)

**Comment by drivebyer** [comment]
Nice catch! May be the first method is better, becouse it's better to unit test and it's more consistent with already code.
