### ISSUE TITLE
Make metrics-exporter container optional and configurable image

### ISSUE THREAD

**Issue by TomerG711** [bitpoke/mysql-operator#785]
Hi,
My team and I have recently installed the MySQL operator for setting up MySQL cluster.
However, we run on-prem and we've encountered some issues when we created a cluster.
When the statefulset of the cluster is created, it creates pods with multiple containers, one of them is metrics-exporter. This container is based on the image: prom/mysqld-exporter:v0.13.0. It is not configurable, and thus the container cannot be created.

Is it possible to change the MysqlCluster CRD so that the metric-exporter container (under the statefulset created) can be optional? 

In addition, is it possible to add the metrics-exporter image to the values.yaml file so it can be configured (The same as the rest of the images) ? It'll be very useful for on-prem setups.

Also, are there any other solutions you can suggest us that'll fix it?

**Comment by jiuker** [comment]
you can do with:   operator/values.yaml
extraArgs: ["--metrics-exporter-image=image:tag"]

**Comment by TomerG711** [comment]
> you can do with: operator/values.yaml extraArgs: ["--metrics-exporter-image=image:tag"]

It works, thanks!
