### ISSUE TITLE
Max backup size

### ISSUE THREAD

**Issue by elderapo** [bitpoke/mysql-operator#791]
Just realized there is this line in the logs:
```
2022/02/10 07:07:05 NOTICE: S3 bucket ***redacted*** path mysql-database-cluster-production: Streaming uploads using chunk size 5Mi will have maximum file size of 48.828Gi
```

Does it mean that the maximum database backup size that can be uploaded to S3 is ~48.8 GB? I am slowly approaching this limit and haven't tested if it fails but would love to get some feedback.

**Comment by calind** [comment]
You should be able to specify

```yaml
spec:
  rcloneExtraArgs:
    - --s3-chunk-size=10Mi
```

You can set the chunk size up to 5Gi (according to https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html).

Please reopen if this does not fix the issue.
