### ISSUE TITLE
Release 0.6.3

### ISSUE THREAD

**Issue by panpan0000** [bitpoke/mysql-operator#840]
the last tag 0.6.2 was 9 month ago..

**Comment by yankay** [comment]
HI  @cndoit18 , Should we release a new version?

**Comment by cndoit18** [comment]
cc @calind

**Comment by panpan0000** [comment]
Hey, Dear @calind , can you please help ? Or is there any release process which somebody else can offload the work when you are busy?

**Comment by yankay** [comment]
HI @calind, 

Look forward a new version :-)

**Comment by xulongju** [comment]
HI @calind,

Please type a new tag，thanks！

**Comment by calind** [comment]
Will look into merged code and make the release.

**Comment by yunussandikci** [comment]
I am looking forward to the release since it includes a pt-heartbeat resource setting 🙂

**Comment by yunussandikci** [comment]
Hello @calind, 
First of all, thanks a lot for this great project. Secondly, Is there any ETA for the new release? 
Thanks!

**Comment by vega-punk** [comment]
HI @calind,
Look forward a new version, suppoert 8.0.28

**Comment by w33dw0r7d** [comment]
> Is there any update about the new release? Due to PodDisruptionBudget in policy/v1beta1 being removed in kubernetes 1.25 it's impossible to proceed with upgrade. EOL for 1.24 is 2023-07-28... The fix for this has been already merged but due to missing release it's not deployable.

I tired wait and rebuild image from master locally. All work fine.

**Comment by nick4fake** [comment]
@jiuker Have you managed to run it on k8s v > 1.25? Orchestrator doesn't work even with your latest version due to podsecuritypolice being removed

**Comment by jiuker** [comment]
> @jiuker Have you managed to run it on k8s v > 1.25? Orchestrator doesn't work even with your latest version due to podsecuritypolice being removed
 
what's the log @nick4fake

**Comment by drivebyer** [comment]
v0.6.3 released! https://github.com/bitpoke/mysql-operator/releases/tag/v0.6.3
