### ISSUE TITLE
no failover when master node is down

### ISSUE THREAD

**Issue by hunterhe23** [bitpoke/mysql-operator#880]
test with my cluster.
when mysql master pod is down, it failover to other pod successfully.
but when the node which runs master pod is down, it doesn‘t failover.
that is unexpected.
what maybe wrong?
thank you.

**Comment by HappyUncle** [comment]
Please attach the orchestrator log.

**Comment by hunterhe23** [comment]
> Please attach the orchestrator log.

i just made a wrong test.
it could failover when the node which runs mysql master is down, thanks.
