### ISSUE TITLE
pvc was deleted when mysqlCluster cr deleted

### ISSUE THREAD

**Issue by sfeng1996** [bitpoke/mysql-operator#892]
when i use  kubectl tool to delete mysqlcluster resoure ,it make the pvc resource was deleted soon, 
so how  to prevent   the pvc resoure to be deleted when i just want to shutdown mysqlcluster
or recreate mysqlcluster but do not want to destory data in mysqlcluster.

**Comment by drivebyer** [comment]
It seems no workaround, maybe we can add option to control it.
