### ISSUE TITLE
Checking in: is the MySQL-operator project still active?

### ISSUE THREAD

**Issue by jyje** [bitpoke/mysql-operator#917]
Hello 😊

It seems like this project provides excellent support for the mysql-operator I intend to use. However, I've noticed there haven't been any recent commits, leading me to wonder about the project's current status.

Checking the README, I saw the last roadmap update was in Feb 2023. This makes me a bit concerned about whether the project is still being actively maintained, which could make it challenging to receive support or contribute code. This prompted me to write this issue. Are the project maintainers still active? Please let me know

**Comment by drivebyer** [comment]
It's said that this project isn't very active lately. However, it has been stable in my experience. I suggest you thoroughly test it in your own environment to see if it meets your needs.

**Comment by jyje** [comment]
Thank you!
